[tool.isort]
profile = "black"

[tool.pyright]
pythonVersion = "3.11.*"

reportMissingImports = false
reportMissingModuleSource = false
reportUnknownParameterType = true
reportUnknownArgumentType = true
reportMissingTypeArgument = true
reportMissingParameterType = true
